class Models {
  const Models._();

  static const _baseImages = 'assets/model_images';

  static List<String> kusumoAnimals = [
    "ayam mutiara",
    "babi rusa",
    "banteng jawa",
    "bekantan",
    "berang-berang",
    "beruang madu",
    "binturong",
    "burung unta",
    "eland",
    "gajah",
    "harimau",
    "jalak bali",
    "jerapah",
    "julang sulawesi",
    "kakatua",
    "kambing gunung",
    "kangkareng perut putih",
    "kasuari",
    "kijang",
    "komodo",
    "kroonkan",
    "kuda",
    "kuda nil",
    "landak jawa",
    "lutung jawa",
    "merak",
    "onta",
    "orangutan",
    "pelikan",
    "rakun",
    "rangkong badak",
    "rusa",
    "siamang",
    "singa",
    "sitatunga",
    "walabi",
    "watusi",
    "wildebeest biru",
    "zebra"
  ];

  static List<String> kusumoAnimalDesc = [
    "Burung berukuran sedang dengan bulu berwarna abu-abu berbintik putih, sering dipelihara sebagai unggas hias.",
    "Mamalia endemik Sulawesi dengan taring melengkung ke belakang, hidup di hutan tropis.",
    "Spesies sapi liar endemik Jawa dengan tubuh kekar dan tanduk melengkung.",
    "Primata berhidung panjang yang hidup di hutan bakau Kalimantan.",
    "Mamalia semiakuatik yang pandai berenang dan membangun sarang di tepi sungai.",
    "Beruang terkecil di dunia dengan bulu hitam dan bercak kuning di dada.",
    "Mamalia nokturnal dengan bau khas seperti popcorn, hidup di hutan tropis.",
    "Burung terbesar yang tidak bisa terbang, berasal dari Afrika dengan leher dan kaki panjang.",
    "Antelop besar dengan tanduk spiral, hidup di padang rumput Afrika.",
    "Mamalia darat terbesar dengan belalai panjang, hidup di Asia dan Afrika.",
    "Kucing besar dengan pola belang, predator puncak di ekosistemnya.",
    "Burung endemik Bali dengan bulu putih dan jambul biru, sangat terancam punah.",
    "Mamalia berkaki panjang dengan leher sangat panjang, hidup di savana Afrika.",
    "Burung besar dengan paruh besar dan kantung tenggorokan, endemik Sulawesi.",
    "Burung berwarna cerah dengan jambul khas, dikenal karena kemampuan menirukan suara.",
    "Mamalia herbivora yang hidup di pegunungan terjal, ahli dalam memanjat tebing curam.",
    "Burung berwarna hitam-putih dengan paruh besar dan kantung tenggorokan yang khas.",
    "Burung besar tidak bisa terbang dari Papua dan Australia, dengan tubuh kokoh dan kepala berwarna biru mencolok.",
    "Hewan pemakan tumbuhan bertubuh ramping, gesit, dan sering dijumpai di hutan atau padang rumput.",
    "Kadal terbesar di dunia, endemik Indonesia, dengan air liur yang mengandung bakteri mematikan.",
    "Mamalia besar dengan tanduk panjang dan melengkung, sering dikaitkan dengan budaya Afrika.",
    "Mamalia berkuku satu yang telah lama dijinakkan untuk transportasi dan kerja.",
    "Mamalia semiakuatik besar dengan tubuh bulat dan mulut lebar, hidup di sungai dan danau Afrika.",
    "Mamalia kecil dengan tubuh berduri, aktif di malam hari dan menggulung diri saat terancam.",
    "Primata endemik Jawa dengan bulu abu-abu kehitaman dan ekor panjang.",
    "Burung berwarna cerah dengan ekor panjang yang dapat dikembangkan seperti kipas.",
    "Mamalia gurun dengan punuk di punggungnya, digunakan sebagai hewan beban.",
    "Primata besar yang hidup di hutan tropis, dikenal karena kecerdasannya.",
    "Burung air besar dengan paruh panjang dan kantung di bawahnya untuk menangkap ikan.",
    "Mamalia kecil dengan wajah seperti topeng dan ekor lebat, aktif di malam hari.",
    "Burung besar dengan paruh besar dan tanduk di atasnya, hidup di hutan tropis.",
    "Mamalia berkaki empat dengan tanduk, hidup di hutan dan padang rumput.",
    "Primata arboreal dengan lengan panjang, dikenal karena panggilannya yang nyaring.",
    "Kucing besar dengan surai di leher jantan, dikenal sebagai 'raja hutan'.",
    "Antelop semi-akuatik yang hidup di daerah rawa dan lahan basah, dikenal dengan kemampuan berenangnya.",
    "Marsupial kecil yang hidup di Australia dan Papua, aktif di malam hari.",
    "Sapi domestik dengan tanduk besar dan melengkung, berasal dari Afrika.",
    "Jenis antelop besar dari Afrika, bermigrasi dalam kelompok besar untuk mencari padang rumput baru.",
    "Mamalia berkuku satu dengan pola garis hitam-putih di tubuhnya, hidup di padang rumput Afrika."
  ];

  static List<String> kusumoAnimalLatins = [
    "Numida meleagris",
    "Babyrousa babyrussa",
    "Bos javanicus javanicus",
    "Nasalis larvatus",
    "Lutra lutra",
    "Helarctos malayanus",
    "Arctictis binturong",
    "Struthio camelus",
    "Taurotragus oryx",
    "Elephas maximus",
    "Panthera tigris",
    "Leucopsar rothschildi",
    "Giraffa camelopardalis",
    "Rhyticeros cassidix",
    "Cacatua spp.",
    "Capra ibex",
    "Anthracoceros albirostris",
    "Casuarius casuarius",
    "Muntiacus spp.",
    "Varanus komodoensis",
    "Bos taurus africanus",
    "Equus ferus caballus",
    "Hippopotamus amphibius",
    "Hystrix javanica",
    "Trachypithecus auratus",
    "Pavo cristatus",
    "Camelus dromedarius",
    "Pongo pygmaeus",
    "Pelecanus spp.",
    "Procyon lotor",
    "Buceros rhinoceros",
    "Cervus spp.",
    "Symphalangus syndactylus",
    "Panthera leo",
    "Tragelaphus spekii",
    "Macropus spp.",
    "Bos taurus watusi",
    "Connochaetes taurinus",
    "Equus quagga"
  ];

  static List<String> kusumoAnimalUniqueFacts = [
    "Ayam mutiara lebih suka berlari daripada terbang dan dikenal sebagai unggas penjaga karena kepekaannya terhadap gangguan.",
    "Babi rusa memiliki taring atas yang menembus kulit hidung dan melengkung ke belakang, unik di antara mamalia.",
    "Banteng jawa adalah spesies sapi liar yang terancam punah dan hanya ditemukan di beberapa wilayah di Indonesia.",
    "Bekantan jantan memiliki hidung panjang yang digunakan untuk menarik perhatian betina dan memperkuat suara panggilan.",
    "Berang-berang menggunakan batu sebagai alat untuk memecah cangkang makanan seperti kerang.",
    "Beruang madu memiliki lidah panjang hingga 25 cm untuk menjilat madu dari sarang lebah.",
    "Binturong memiliki bau khas seperti popcorn karena senyawa kimia dalam kelenjar analnya.",
    "Burung unta memiliki mata terbesar di antara hewan darat, bahkan lebih besar dari otaknya.",
    "Eland dapat melompat setinggi 2,5 meter meskipun memiliki tubuh besar dan berat.",
    "Gajah dapat mengenali diri mereka sendiri di cermin, menunjukkan tingkat kesadaran diri yang tinggi.",
    "Harimau adalah satu-satunya kucing besar yang suka berenang dan sering mandi untuk mendinginkan tubuh.",
    "Jalak bali adalah burung endemik Indonesia yang sangat langka dan menjadi simbol konservasi.",
    "Jerapah hanya tidur sekitar 30 menit hingga 2 jam per hari, biasanya dalam posisi berdiri.",
    "Julang sulawesi jantan menutup sarang betina dengan lumpur selama masa pengeraman untuk melindungi telur.",
    "Kakatua dapat menirukan suara manusia dan memiliki kemampuan kognitif yang tinggi.",
    "Kambing gunung memiliki kuku khusus yang mencengkeram batu dengan kuat, memungkinkan mereka memanjat tebing curam.",
    "Kangkareng perut putih dikenal aktif berbunyi dan hidup berpasangan atau berkelompok.",
    "Kasuari bisa berlari hingga 50 km/jam dan memiliki cakar tajam yang berbahaya.",
    "Beberapa jenis kijang memiliki taring yang menonjol keluar dari rahang.",
    "Komodo memiliki air liur yang mengandung bakteri mematikan yang membantu melumpuhkan mangsanya.",
    "Kroonkan adalah sapi domestik dengan tanduk besar dan melengkung, sering dikaitkan dengan budaya Afrika.",
    "Kuda telah digunakan sebagai alat transportasi dan dalam pertanian selama ribuan tahun.",
    "Kuda nil menghabiskan sebagian besar waktunya di air untuk menjaga suhu tubuh tetap stabil.",
    "Landak jawa menggulung tubuhnya menjadi bola berduri sebagai mekanisme pertahanan.",
    "Lutung jawa memiliki ekor panjang yang membantu menjaga keseimbangan saat bergerak di pepohonan.",
    "Merak jantan mengembangkan ekor berwarna cerah untuk menarik perhatian betina saat musim kawin.",
    "Onta dapat bertahan tanpa air selama beberapa minggu dengan menyimpan lemak di punuknya.",
    "Orangutan menggunakan alat sederhana seperti ranting untuk mengambil serangga atau madu.",
    "Pelikan memiliki kantung di bawah paruhnya yang digunakan untuk menangkap dan menyaring ikan.",
    "Rakun dikenal karena kebiasaannya mencuci makanan sebelum dimakan, meskipun tidak selalu diperlukan.",
    "Rangkong badak memiliki struktur seperti tanduk di atas paruhnya yang digunakan dalam pertarungan dan menarik pasangan.",
    "Rusa jantan menggugurkan dan menumbuhkan kembali tanduknya setiap tahun sebagai bagian dari siklus reproduksi.",
    "Siamang memiliki kantung tenggorokan yang membesar untuk menghasilkan suara panggilan keras yang bisa terdengar hingga 3 km.",
    "Singa adalah satu-satunya kucing besar yang hidup dalam kelompok sosial yang disebut kawanan.",
    "Sitatunga memiliki kuku yang lebar dan lentur, memungkinkan mereka berjalan di lahan rawa tanpa tenggelam.",
    "Walabi bisa melompat sejauh 2 meter dan merupakan kerabat dekat kanguru dari Australia.",
    "Watusi dikenal dengan tanduk raksasanya yang bisa mencapai panjang lebih dari 2 meter, digunakan untuk pendinginan tubuh.",
    "Wildebeest biru bermigrasi dalam kelompok besar yang bisa mencapai jutaan individu, salah satu migrasi terbesar di daratan.",
    "Zebra memiliki pola garis unik seperti sidik jari, tidak ada dua zebra dengan pola yang sama."
  ];

  static List<String> kusumoImagePaths = [
    '$_baseImages/ayam_mutiara.png',
    '$_baseImages/babi_rusa.png',
    '$_baseImages/banteng_jawa.png',
    '$_baseImages/bekantan.png',
    '$_baseImages/berang_berang.png',
    '$_baseImages/beruang_madu.png',
    '$_baseImages/binturong.png',
    '$_baseImages/burung_unta.png',
    '$_baseImages/eland.png',
    '$_baseImages/gajah.png',
    '$_baseImages/harimau.png',
    '$_baseImages/jalak_bali.png',
    '$_baseImages/jerapah.png',
    '$_baseImages/julang_sulawesi.png',
    '$_baseImages/kakatua.png',
    '$_baseImages/kambing_gunung.png',
    '$_baseImages/kangkareng_perut_putih.png',
    '$_baseImages/kasuari.png',
    '$_baseImages/kijang.png',
    '$_baseImages/komodo.png',
    '$_baseImages/kroonkan.png',
    '$_baseImages/kuda.png',
    '$_baseImages/kuda_nil.png',
    '$_baseImages/landak_jawa.png',
    '$_baseImages/lutung_jawa.png',
    '$_baseImages/merak.png',
    '$_baseImages/onta.png',
    '$_baseImages/orangutan.png',
    '$_baseImages/pelikan.png',
    '$_baseImages/rakun.png',
    '$_baseImages/rangkong_badak.png',
    '$_baseImages/rusa.png',
    '$_baseImages/siamang.png',
    '$_baseImages/singa.png',
    '$_baseImages/sitatunga.png',
    '$_baseImages/walabi.png',
    '$_baseImages/watusi.png',
    '$_baseImages/wildebeest_biru.png',
    '$_baseImages/zebra.png',
  ];

  static List<String> auliyaAnimals = [
    "Eland",
    "Kambing Gunung",
    "Kijang",
    "Sitatunga",
    "Wildebeest Biru",
    "Aves",
    "Julang Sulawesi",
    "Kangkareng Perut Putih",
    "Kasuari",
  ];

  static List<String> auliyaAnimalDesc = [
    "Antelop terbesar di dunia, hidup di padang rumput Afrika, memiliki tanduk spiral dan tubuh kekar.",
    "Mamalia herbivora yang hidup di pegunungan terjal, ahli dalam memanjat tebing curam.",
    "Hewan pemakan tumbuhan bertubuh ramping, gesit, dan sering dijumpai di hutan atau padang rumput.",
    "Antelop semi-akuatik yang hidup di daerah rawa dan lahan basah, dikenal dengan kemampuan berenangnya.",
    "Jenis antelop besar dari Afrika, bermigrasi dalam kelompok besar untuk mencari padang rumput baru.",
    "Kelas hewan vertebrata bersayap, memiliki bulu dan sebagian besar mampu terbang.",
    "Burung endemik Sulawesi dengan paruh besar dan unik, aktif menjaga anaknya dalam sarang selama masa pengeraman.",
    "Burung besar berwarna hitam-putih dengan paruh besar dan kantung tenggorokan yang khas.",
    "Burung besar tidak bisa terbang dari Papua dan Australia, dengan tubuh kokoh, kaki kuat, dan kepala berwarna biru mencolok.",
  ];

  static List<String> auliyaAnimalLatins = [
    "Taurotragus oryx",
    "Capra ibex",
    "Muntiacus spp.",
    "Tragelaphus spekii",
    "Connochaetes taurinus",
    "Aves (kelas)",
    "Rhyticeros cassidix",
    "Anthracoceros albirostris",
    "Casuarius casuarius",
  ];

  static List<String> auliyaAnimalUniqueFacts = [
    "Eland bisa melompat hingga lebih dari 2 meter meski tubuhnya besar.",
    "Kambing gunung memiliki kuku khusus yang mencengkeram batu dengan kuat.",
    "Beberapa jenis kijang memiliki taring yang menonjol keluar dari rahang.",
    "Sitatunga memiliki kaki panjang dan ramping, ideal untuk berjalan di rawa.",
    "Wildebeest biru berpartisipasi dalam migrasi besar tahunan di Afrika bersama zebra.",
    "Aves adalah satu-satunya kelompok vertebrata yang memiliki bulu sebagai ciri khas utama.",
    "Julang Sulawesi jantan menutup sarang betina dengan lumpur selama masa inkubasi.",
    "Kangkareng Perut Putih dikenal aktif berbunyi dan hidup berpasangan atau berkelompok.",
    "Kasuari bisa berlari hingga 50 km/jam dan memiliki cakar tajam yang berbahaya.",
  ];

  static List<String> auliyaImagePaths = [
    '$_baseImages/eland.png',
    '$_baseImages/kambing_gunung.png',
    '$_baseImages/kijang.png',
    '$_baseImages/sitatunga.png',
    '$_baseImages/wildebeest_biru.png',
    '$_baseImages/aves.png',
    '$_baseImages/julang_sulawesi.png',
    '$_baseImages/kangkareng_perut_putih.png',
    '$_baseImages/kasuari.png',
  ];

  static List<String> fuadahAnimals = [
    "Ikan Dokter",
    "Ikan Moorish Idol",
    "Ikan Komet",
    "Ikan Kepe-kepe",
    "Ikan Angelfish",
    "Ikan Koi",
    "Ikan Koki Oranda",
    "Ikan Mas",
    "Ikan Kaos Kaki",
    "Ikan Oscar",
    "Ikan Buntal",
    "Ikan Nemo",
    "Ikan Lele Ekor Merah",
    "Ikan Pari Motoro",
    "Ikan Piranha Perut Merah",
    "Ikan Koki Ranchu",
    "Ikan Dollar",
    "Ikan Botana Biru",
    "Ikan Buaya Alligator",
    "Ikan Frontosa",
    "Ikan Arwana",
    "Ikan Kuda Laut",
    "Ikan Tombro",
    "Ikan Betok Karang",
    "Ikan Neoniphon",
    "Ikan Scorpion",
  ];

  static List<String> fuadahAnimalDesc = [
    "Ikan laut dari keluarga Acanthuridae dengan duri tajam seperti pisau bedah, berfungsi sebagai pembersih alami terumbu karang.",
    "Ikan laut ikonik dengan tubuh pipih dan warna mencolok, sulit dipelihara di akuarium.",
    "Varietas ikan mas hias dengan ekor panjang dan warna cerah, cocok untuk kolam hias.",
    "Ikan laut tropis dengan warna mencolok menyerupai kupu-kupu, hidup di terumbu karang.",
    "Ikan hias laut dengan tubuh pipih dan sirip anggun, bersifat teritorial dan makan spons serta alga.",
    "Ikan hias air tawar dengan corak warna indah, simbol keberuntungan di budaya Asia.",
    "Ikan mas koki dengan benjolan daging di kepala, gerakan lambat dan anggun.",
    "Ikan air tawar populer, mudah dipelihara dan memiliki variasi warna.",
    "Ikan hias air tawar dengan pola menyerupai kaos kaki, tampilannya unik.",
    "Ikan predator air tawar yang cerdas dan bisa mengenali pemiliknya, cocok untuk akuarium besar.",
    "Ikan yang bisa menggelembungkan tubuh saat terancam, beberapa spesiesnya beracun.",
    "Ikan laut kecil oranye dengan garis putih, hidup bersimbiosis dengan anemon laut.",
    "Ikan predator besar dari Amerika Selatan, dikenal karena ekor merah mencolok.",
    "Ikan pari air tawar dengan pola tutul menyerupai mata, berasal dari sungai Amazon.",
    "Ikan predator dengan gigi tajam dan perut merah mencolok, karnivora ganas.",
    "Varietas ikan koki tanpa sirip punggung dan benjolan besar di kepala.",
    "Ikan air tawar berbentuk seperti koin perak, hidup berkelompok.",
    "Ikan laut biru terang dengan ekor kuning, dikenal sebagai Dory.",
    "Ikan predator dengan moncong panjang dan sisik keras, termasuk spesies purba.",
    "Ikan dari Danau Tanganyika dengan tonjolan kepala dan garis biru-hitam.",
    "Ikan hias besar dengan sisik mengkilap, dianggap membawa keberuntungan.",
    "Ikan laut unik dengan bentuk menyerupai kuda, jantan mengandung telur.",
    "Ikan konsumsi dan hias dengan tubuh besar, mudah dibudidayakan.",
    "Ikan laut kecil dengan garis vertikal hitam, seperti seragam militer.",
    "Ikan laut malam aktif berwarna merah terang dengan mata besar.",
    "Ikan laut dengan kamuflase dan duri beracun, predator penyergap.",
  ];

  static List<String> fuadahAnimalLatins = [
    "Paracanthurus hepatus",
    "Zanclus cornutus",
    "Carassius auratus ‘Comet’",
    "Chaetodontidae",
    "Pomacanthidae",
    "Cyprinus rubrofuscus",
    "Carassius auratus ‘Oranda’",
    "Carassius auratus",
    "Tidak diketahui (nama umum)",
    "Astronotus ocellatus",
    "Tetraodontidae",
    "Amphiprion ocellaris",
    "Phractocephalus hemioliopterus",
    "Potamotrygon motoro",
    "Pygocentrus nattereri",
    "Carassius auratus ‘Ranchu’",
    "Metynnis spp.",
    "Paracanthurus hepatus",
    "Atractosteus spatula",
    "Cyphotilapia frontosa",
    "Scleropages spp.",
    "Hippocampus spp.",
    "Cyprinus carpio",
    "Abudefduf spp.",
    "Neoniphon sammara",
    "Scorpaenidae",
  ];

  static List<String> fuadahUniqueFacts = [
    "Disebut 'ikan dokter' karena membantu membersihkan terumbu karang dari alga dan parasit.",
    "Nama 'Moorish Idol' berasal dari kepercayaan masyarakat Afrika Utara bahwa ikan ini membawa keberuntungan.",
    "Ikan komet dikenal karena kecepatannya berenang dan daya tahannya terhadap kondisi air yang kurang ideal.",
    "Coraknya menyerupai kupu-kupu, membuatnya disebut butterflyfish.",
    "Angelfish memiliki suara klik saat berkomunikasi satu sama lain.",
    "Koi bisa hidup hingga puluhan tahun, bahkan ada yang tercatat hidup lebih dari 200 tahun.",
    "Benjolan di kepala ikan Oranda disebut 'wen', dan bisa tumbuh cukup besar jika sehat.",
    "Ikan mas pertama kali dibudidayakan di Tiongkok lebih dari 1.000 tahun lalu.",
    "Dijuluki 'ikan kaos kaki' karena pola putih di sirip menyerupai kaos kaki bayi.",
    "Oscar bisa dilatih untuk makan dari tangan dan bereaksi terhadap pemiliknya.",
    "Beberapa jenis ikan buntal memiliki racun tetrodotoxin yang lebih mematikan dari sianida.",
    "Clownfish jantan menjaga dan merawat telur-telurnya sampai menetas.",
    "Redtail catfish bisa tumbuh hingga lebih dari 1 meter dan tidak cocok dipelihara di akuarium kecil.",
    "Pari Motoro bisa 'mengubur' dirinya di pasir untuk bersembunyi dari predator.",
    "Piranha hanya menyerang dalam kelompok dan saat mereka lapar atau terganggu.",
    "Ranchu sering disebut 'raja koki' karena bentuk tubuhnya yang paling unik dan elegan.",
    "Silver Dollar dinamai demikian karena bentuk tubuhnya mirip koin perak besar.",
    "Dory dari film Finding Nemo adalah seekor Blue Tang betina.",
    "Alligator Gar bisa bernapas udara langsung dan hidup di air dengan oksigen rendah.",
    "Frontosa hanya ada di Danau Tanganyika dan memiliki sifat yang sangat tenang.",
    "Arwana dipercaya membawa hoki dan rezeki, khususnya yang berwarna merah.",
    "Kuda laut jantan yang mengandung dan melahirkan anak-anaknya.",
    "Tombro dapat hidup di perairan keruh dan tahan terhadap perubahan suhu drastis.",
    "Betok karang dapat berubah warna untuk menyesuaikan lingkungan.",
    "Neoniphon aktif di malam hari dan memiliki penglihatan yang sangat tajam di gelap.",
    "Scorpionfish bisa berkamuflase hingga nyaris tak terlihat oleh mangsanya."
  ];

  static List<String> fuadahImagePaths = [
    '$_baseImages/ikan_dokter.png',
    '$_baseImages/ikan_moorish_idol.png',
    '$_baseImages/ikan_komet.png',
    '$_baseImages/ikan_kepe_kepe.png',
    '$_baseImages/ikan_angelfish.png',
    '$_baseImages/ikan_koi.png',
    '$_baseImages/ikan_koki_oranda.png',
    '$_baseImages/ikan_mas.png',
    '$_baseImages/ikan_kaos_kaki.png',
    '$_baseImages/ikan_oscar.png',
    '$_baseImages/ikan_buntal.png',
    '$_baseImages/ikan_nemo.png',
    '$_baseImages/ikan_lele_ekor_merah.png',
    '$_baseImages/ikan_pari_motoro.png',
    '$_baseImages/ikan_piranha_perut_merah.png',
    '$_baseImages/ikan_koki_ranchu.png',
    '$_baseImages/ikan_dollar.png',
    '$_baseImages/ikan_botana_biru.png',
    '$_baseImages/ikan_buaya_alligator.png',
    '$_baseImages/ikan_frontosa.png',
    '$_baseImages/ikan_arwana.png',
    '$_baseImages/ikan_kuda_laut.png',
    '$_baseImages/ikan_tombro.png',
    '$_baseImages/ikan_betok_karang.png',
    '$_baseImages/ikan_neoniphon.png',
    '$_baseImages/ikan_scorpion.png',
  ];
}
